# Generated by Django 4.0.5 on 2022-07-08 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0003_curso_creditos_malla_anio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrematriCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('desc', models.TextField(null=True)),
                ('estReg', models.BooleanField(default=True)),
                ('escuela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='PrematriCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estReg', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.curso')),
                ('prematriCab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prematricula.prematricab')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrematriCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estReg', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prematriCurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prematricula.prematricurso')),
            ],
        ),
    ]
