# Generated by Django 4.0.5 on 2022-07-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('semejante', models.CharField(max_length=10, null=True)),
                ('prereq', models.CharField(max_length=64, null=True)),
                ('desc', models.TextField(null=True)),
                ('estReg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=48)),
                ('desc', models.TextField(null=True)),
                ('estReg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrematriCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('desc', models.TextField(null=True)),
                ('estReg', models.BooleanField(default=True)),
                ('escuela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='PrematriCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estReg', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.curso')),
                ('prematriCab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.prematricab')),
            ],
        ),
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(null=True)),
                ('estReg', models.BooleanField(default=True)),
                ('escuela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.escuela')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='malla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.malla'),
        ),
    ]
