# Generated by Django 4.0.5 on 2022-07-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prematricurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='prematricurso',
            name='prematriCab',
        ),
        migrations.DeleteModel(
            name='PrematriCab',
        ),
        migrations.DeleteModel(
            name='PrematriCurso',
        ),
    ]
