# Generated by Django 4.0.5 on 2022-08-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0003_curso_creditos_malla_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
